package it.palsoftware.pastiera.inputmethod.composition

internal enum class CompositionFinishReason {
    BOUNDARY, ENTER, PUNCTUATION, COMMAND, CURSOR_MOVE, SELECTION_CHANGE,
    LAYOUT_SWITCH, SUBTYPE_SWITCH, LANGUAGE_SWITCH, SUGGESTION_COMMIT,
    TRACKPAD_SUGGESTION_COMMIT, TRACKPAD_DELETE_WORD, CLIPBOARD, EMOJI,
    UNICODE_PICKER, VOICE_INPUT, TEXT_EXPANSION, VARIATION, SYMBOL,
    INTERNAL_INPUT_CAPTURE, IME_ACTION, INPUT_FINISH, WINDOW_HIDDEN,
    MAX_LENGTH_INTERNAL_SPLIT
}
