#!/usr/bin/env python3
"""Update bundled emoji assets from Unicode Emoji data.

This keeps the existing Pastiera asset format:
- app/src/main/assets/common/emoji/*.txt: picker categories, one base emoji per line
  followed by variants.
- app/src/main/assets/common/emoji/minApi.txt: optional SDK gates for native-font
  emoji support.

Search TSVs are intentionally generated by scripts/generate_emoji_search_assets.py
after this script updates the picker assets.
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
from collections import OrderedDict
from pathlib import Path


EMOJI_TEST_URL = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
CLDR_ANNOTATIONS_URL = (
    "https://raw.githubusercontent.com/unicode-org/cldr-json/main/"
    "cldr-json/cldr-annotations-full/annotations/en/annotations.json"
)

GROUP_TO_FILE = {
    "Smileys & Emotion": "SMILEYS_AND_EMOTION.txt",
    "People & Body": "PEOPLE_AND_BODY.txt",
    "Animals & Nature": "ANIMALS_AND_NATURE.txt",
    "Food & Drink": "FOOD_AND_DRINK.txt",
    "Travel & Places": "TRAVEL_AND_PLACES.txt",
    "Activities": "ACTIVITIES.txt",
    "Objects": "OBJECTS.txt",
    "Symbols": "SYMBOLS.txt",
    "Flags": "FLAGS.txt",
}

VERSION_TO_MIN_API = {
    "E4.0": 24,
    "E5.0": 26,
    "E11.0": 28,
    "E12.0": 29,
    "E12.1": 29,
    "E13.0": 30,
    "E13.1": 31,
    "E14.0": 32,
    "E15.0": 33,
    "E15.1": 34,
    "E16.0": 35,
}

SKIN_TONES = {chr(cp) for cp in range(0x1F3FB, 0x1F400)}


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parents[1]


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def codepoints_to_emoji(codepoints: str) -> str:
    return "".join(chr(int(cp, 16)) for cp in codepoints.split())


def emoji_to_unified(emoji: str) -> str:
    return "-".join(f"{ord(ch):04X}" for ch in emoji)


def shortcode_from_name(name: str) -> str:
    out = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return out or "emoji"


def strip_skin_tones(emoji: str) -> str:
    return "".join(ch for ch in emoji if ch not in SKIN_TONES)


def parse_emoji_test(text: str) -> tuple[str, list[dict[str, str]]]:
    version = "unknown"
    group = ""
    subgroup = ""
    records: list[dict[str, str]] = []

    for line in text.splitlines():
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
        elif line.startswith("# group:"):
            group = line.split(":", 1)[1].strip()
        elif line.startswith("# subgroup:"):
            subgroup = line.split(":", 1)[1].strip()

        if "; fully-qualified" not in line:
            continue

        codepoints, rest = line.split(";", 1)
        emoji = codepoints_to_emoji(codepoints.strip())
        status = rest.split("#", 1)[0].strip()
        if status != "fully-qualified":
            continue

        comment = line.split("#", 1)[1].strip()
        comment_parts = comment.split(" ", 2)
        emoji_version = comment_parts[1] if len(comment_parts) > 1 else ""
        name = comment_parts[2] if len(comment_parts) > 2 else comment

        records.append(
            {
                "emoji": emoji,
                "version": emoji_version,
                "name": name,
                "group": group,
                "subgroup": subgroup,
            }
        )

    return version, records


def load_category_files(emoji_dir: Path) -> tuple[dict[str, list[list[str]]], dict[str, tuple[str, int]]]:
    files: dict[str, list[list[str]]] = OrderedDict()
    token_locations: dict[str, tuple[str, int]] = {}

    for file_name in GROUP_TO_FILE.values():
        path = emoji_dir / file_name
        lines: list[list[str]] = []
        for line in path.read_text(encoding="utf-8").splitlines():
            tokens = [token for token in line.split(" ") if token]
            if not tokens:
                continue
            line_index = len(lines)
            lines.append(tokens)
            for token in tokens:
                token_locations[token] = (file_name, line_index)
        files[file_name] = lines

    return files, token_locations


def load_min_api(path: Path) -> OrderedDict[int, list[str]]:
    out: OrderedDict[int, list[str]] = OrderedDict()
    for line in path.read_text(encoding="utf-8").splitlines():
        tokens = [token for token in line.split(" ") if token]
        if not tokens:
            continue
        api = int(tokens[0])
        out[api] = tokens[1:]
    return out


def min_api_for_version(version: str, emoji17_min_api: int) -> int | None:
    if version == "E17.0":
        return emoji17_min_api
    return VERSION_TO_MIN_API.get(version)


def update_categories(
    emoji_dir: Path,
    records: list[dict[str, str]],
    emoji17_min_api: int,
) -> tuple[int, list[dict[str, str]]]:
    files, token_locations = load_category_files(emoji_dir)
    local_tokens = set(token_locations)
    added_records: list[dict[str, str]] = []
    new_lines_by_file: dict[str, OrderedDict[str, list[str]]] = {
        file_name: OrderedDict() for file_name in GROUP_TO_FILE.values()
    }

    for record in records:
        emoji = record["emoji"]
        if emoji in local_tokens:
            continue

        file_name = GROUP_TO_FILE.get(record["group"])
        if not file_name:
            continue

        base = strip_skin_tones(emoji)
        if base in token_locations and emoji != base:
            base_file, line_index = token_locations[base]
            if emoji not in files[base_file][line_index]:
                files[base_file][line_index].append(emoji)
                token_locations[emoji] = (base_file, line_index)
                local_tokens.add(emoji)
                added_records.append(record)
            continue

        grouped = new_lines_by_file[file_name].setdefault(base, [])
        if emoji == base:
            grouped.insert(0, emoji)
        elif emoji not in grouped:
            grouped.append(emoji)
        token_locations[emoji] = (file_name, -1)
        local_tokens.add(emoji)
        added_records.append(record)

    for file_name, grouped_lines in new_lines_by_file.items():
        for base, tokens in grouped_lines.items():
            if base not in tokens:
                tokens.insert(0, base)
            deduped = list(OrderedDict.fromkeys(tokens))
            files[file_name].append(deduped)

    for file_name, lines in files.items():
        path = emoji_dir / file_name
        path.write_text(
            "".join(" ".join(tokens) + "\n" for tokens in lines),
            encoding="utf-8",
        )

    min_api_path = emoji_dir / "minApi.txt"
    min_api = load_min_api(min_api_path)
    known_gated = {emoji for emojis in min_api.values() for emoji in emojis}
    for record in added_records:
        api = min_api_for_version(record["version"], emoji17_min_api)
        if api is None or api < 23 or record["emoji"] in known_gated:
            continue
        min_api.setdefault(api, []).append(record["emoji"])
        known_gated.add(record["emoji"])

    min_api_path.write_text(
        "".join(f"{api} {' '.join(emojis)}\n" for api, emojis in sorted(min_api.items())),
        encoding="utf-8",
    )

    return len(added_records), added_records


def load_cldr_names() -> dict[str, str]:
    payload = json.loads(fetch_text(CLDR_ANNOTATIONS_URL))
    annotations = payload["annotations"]["annotations"]
    names: dict[str, str] = {}
    for emoji, record in annotations.items():
        tts = record.get("tts") if isinstance(record, dict) else None
        if isinstance(tts, list) and tts:
            names[emoji] = str(tts[0])
    return names


def update_shortcode_json(path: Path, records: list[dict[str, str]]) -> int:
    existing = json.loads(path.read_text(encoding="utf-8"))
    existing_by_unified = {item.get("unified"): item for item in existing if isinstance(item, dict)}
    cldr_names = load_cldr_names()
    added = 0

    for record in records:
        emoji = record["emoji"]
        if any(tone in emoji for tone in SKIN_TONES):
            continue
        unified = emoji_to_unified(emoji)
        if unified in existing_by_unified:
            continue

        name = cldr_names.get(emoji, record["name"]).upper()
        short_name = shortcode_from_name(cldr_names.get(emoji, record["name"]))
        existing.append(
            {
                "name": name,
                "unified": unified,
                "non_qualified": None,
                "docomo": None,
                "au": None,
                "softbank": None,
                "google": None,
                "image": unified.lower() + ".png",
                "sheet_x": 0,
                "sheet_y": 0,
                "short_name": short_name,
                "short_names": [short_name],
                "text": None,
                "texts": None,
                "category": record["group"],
                "subcategory": record["subgroup"],
                "sort_order": len(existing) + 1,
                "added_in": record["version"].removeprefix("E"),
                "has_img_apple": False,
                "has_img_google": False,
                "has_img_twitter": False,
                "has_img_facebook": False,
            }
        )
        existing_by_unified[unified] = existing[-1]
        added += 1

    path.write_text(json.dumps(existing, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    return added


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--emoji17-min-api",
        type=int,
        default=0,
        help=(
            "Android SDK gate for Emoji 17 entries. Use 0 to expose them on all "
            "devices and let the system font decide rendering support (default: 0)."
        ),
    )
    args = parser.parse_args()

    root = repo_root_from_script()
    emoji_dir = root / "app" / "src" / "main" / "assets" / "common" / "emoji"
    shortcode_json = root / "app" / "src" / "main" / "assets" / "emoji.json"

    emoji_version, records = parse_emoji_test(fetch_text(EMOJI_TEST_URL))
    added_count, added_records = update_categories(emoji_dir, records, args.emoji17_min_api)
    shortcode_count = update_shortcode_json(shortcode_json, added_records)

    print(f"Unicode Emoji {emoji_version}")
    print(f"Added picker entries: {added_count}")
    print(f"Added shortcode entries: {shortcode_count}")
    print("Regenerate search assets with: scripts/generate_emoji_search_assets.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
